# Generated by Django 4.0.4 on 2022-05-03 10:13

from django.db import migrations, models
import hsite.models


class Migration(migrations.Migration):

    dependencies = [
        ('hsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nickname',
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default-avatar.png', upload_to=hsite.models.unique_fname),
        ),
    ]
