# Generated by Django 4.0.4 on 2022-05-03 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hsite', '0002_remove_profile_nickname_alter_profile_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='header',
            new_name='title',
        ),
    ]
