# Generated by Django 4.0.4 on 2022-05-06 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hsite', '0005_votes_question_votes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Votes',
        ),
        migrations.AlterField(
            model_name='question',
            name='votes',
            field=models.ManyToManyField(related_name='user_votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
