# Generated by Django 4.0.4 on 2022-05-06 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hsite', '0006_delete_votes_alter_question_votes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='votes',
            new_name='user_votes',
        ),
    ]
