# Generated by Django 4.0.4 on 2022-05-07 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('hsite', '0007_rename_votes_question_user_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.SmallIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='user_votes',
        ),
        migrations.AddField(
            model_name='question',
            name='users_votes',
            field=models.ManyToManyField(related_name='user_votes', through='hsite.Membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membership',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsite.question'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
