# Generated by Django 4.0.4 on 2022-05-07 08:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hsite', '0008_membership_remove_question_user_votes_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Membership',
            new_name='q2u_m2m',
        ),
    ]
