# Generated by Django 4.0.4 on 2022-05-07 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hsite', '0009_rename_membership_q2u_m2m'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionVotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='users_votes',
            field=models.ManyToManyField(related_name='user_votes', through='hsite.QuestionVotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='q2u_m2m',
        ),
        migrations.AddField(
            model_name='questionvotes',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsite.question'),
        ),
        migrations.AddField(
            model_name='questionvotes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='questionvotes',
            unique_together={('user', 'question')},
        ),
    ]
