# Generated by Django 4.0.4 on 2022-05-08 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hsite', '0010_questionvotes_alter_question_users_votes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerVotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='users_votes',
            field=models.ManyToManyField(related_name='user_a_votes', through='hsite.AnswerVotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='users_votes',
            field=models.ManyToManyField(related_name='user_q_votes', through='hsite.QuestionVotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answervotes',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsite.answer'),
        ),
        migrations.AddField(
            model_name='answervotes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='answervotes',
            unique_together={('user', 'answer')},
        ),
    ]
