# Generated by Django 4.0.4 on 2022-05-08 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hsite', '0013_alter_question_dislikes_alter_question_likes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionvotes',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='questionvotes',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionvotes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='users_votes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='users_votes',
        ),
        migrations.DeleteModel(
            name='AnswerVotes',
        ),
        migrations.DeleteModel(
            name='QuestionVotes',
        ),
    ]
